resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: jmx-consumer-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/jmx-consumer-release

jobs:
- name: run-gradle-tests
  plan:
    - get: jmx-consumer-release
      trigger: true
    - task: run-gradle-tests
      config:
        platform: linux
        inputs:
        - name: jmx-consumer-release
        caches:
        - path: .gradle
        image_resource:
          source:
            repository: openjdk
            tag: 8
          type: docker-image
        run:
          path: bash
          args:
            - -c
            - |
              export GRADLE_USER_HOME=$PWD/.gradle
              cd jmx-consumer-release/src/jmxconsumer
              ./gradlew build