name: jmx-nozzle

releases:
- name: jmx-nozzle
  version: latest

stemcells:
- os: ubuntu-trusty
  alias: ubuntu
  version: latest

instance_groups:
- name: jmx-nozzle
  instances: 1
  jobs:
  - name: jmx-nozzle
    release: jmx-nozzle
    consumes:
      reverse_log_proxy:
        deployment: cf
        from: reverse_log_proxy
    properties:
      tls:
        ca_cert: "((loggregator_ca.certificate))"
        nozzle:
          cert: "((nozzle_ssl.certificate))"
          key: "((nozzle_ssl.private_key))"
      jmx:
        server:
          username: admin
          password: insecure-password

  stemcell: ubuntu
  azs: [z1]
  vm_type: minimal
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000

variables:
- name: nozzle_ssl
  type: certificate
  options:
    ca: loggregator_ca
    common_name: jmx-nozzle
    extended_key_usage:
    - client_auth
    - server_auth
